---
- name: Deploy Docker Image to Docker Hub
  hosts: web01
  tasks:
    - name: Create docker directory on Docker server
      file:
        path: /home/docker
        state: directory
        mode: '0755'

    - name: Copy required files to Docker server
      copy:
        src: "{{ item }}"
        dest: /home/docker/
      loop:
        - /var/lib/jenkins/workspace/sample1/Dockerfile
        - /var/lib/jenkins/workspace/sample1/webapp/target/webapp.war
        - /var/lib/jenkins/workspace/sample1/regapp-deploy.yml

    - name: docker hub login credentails
      shell: docker login -u "{{ docker_username }}" -p "{{ docker_password }}" https://index.docker.io/v1/

    - name: Build Docker Image using shell command
      shell: docker build -t {{ dockerhub_username }}/{{ image_name }}:{{ image_tag }} /home/docker
    
    - name: Push Docker Image to Docker Hub using shell command
      shell: docker push {{ dockerhub_username }}/{{ image_name }}:{{ image_tag }}
  vars_files:
    - /var/lib/jenkins/workspace/sample1/vault.yml
  vars:
    dockerhub_username: "rakarun"
    image_name: "regapp1"
    image_tag: "latest"

